version: "3"
services:
  rust:
    image: prismagraphql/build-image:debian
    environment:
      SERVER_ROOT: /root/build
      COMMIT_SHA: "123abcd"
      RUST_BACKTRACE: "1"
      IS_BUILDKITE: "1"
      RUST_LOG_FORMAT: "devel"
    volumes:
      - ../../..:/root/build
    working_dir: /root/build/prisma-rs
    networks:
      - tests

  test-db-postgres:
    image: postgres:10.3
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs"
    ports:
      - "5432:5432"
    networks:
      - tests
    tmpfs: /pgtmpfs

  test-db-mysql:
    image: mysql:5.7
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3306:3306"
    networks:
      - tests
    tmpfs: /var/lib/mysql

networks:
  tests:
